//GLAN LOADER HEADER LIB
//Ultimate Native OpenGL function loader
//Making things explicit and simple is my goal
//credit: Developed by Thanh Lan Nguyen
//email: lantramnamcodon@gmail.com
typedef char GLchar;
typedef signed long int GLintptr,GLsizeiptr;
typedef GLuint (APIENTRY*PFNGLCREATESHADERPROC)(GLenum type);
typedef void (APIENTRY*PFNGLSHADERSOURCEPROC)(GLuint shader, GLsizei count, GLchar **shit, const GLint *length);
typedef void (APIENTRY*PFNGLCOMPILESHADERPROC)(GLuint shader);
typedef GLuint (APIENTRY*PFNGLCREATEPROGRAMPROC)(void);
typedef void (APIENTRY*PFNGLATTACHSHADERPROC)(GLuint program, GLuint shader);
typedef void (APIENTRY*PFNGLLINKPROGRAMPROC)(GLuint program);
typedef void (APIENTRY*PFNGLUSEPROGRAMPROC)(GLuint program);
typedef void (APIENTRY*PFNGLDETACHSHADERPROC)(GLuint program, GLuint shader);
typedef void (APIENTRY*PFNGLDELETEPROGRAMPROC)(GLuint program);
typedef void (APIENTRY*PFNGLDELETESHADERPROC)(GLuint shader);
typedef void (APIENTRY*PFNGLVERTEXATTRIBPOINTERPROC)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
typedef void (APIENTRY*PFNGLENABLEVERTEXATTRIBARRAYPROC)(GLuint index);
typedef void (APIENTRY*PFNGLGENVERTEXARRAYSPROC)(GLsizei n, GLuint *arrays);
typedef void (APIENTRY*PFNGLBINDVERTEXARRAYPROC)(GLuint array);
typedef void (APIENTRY*PFNGLBINDBUFFERPROC)(GLenum target, GLuint buffer);
typedef void (APIENTRY*PFNGLBUFFERDATAPROC)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
typedef void (APIENTRY*PFNGLGENBUFFERSPROC)(GLsizei n, GLuint *buffers);
typedef void (APIENTRY*PFNGLACTIVETEXTUREPROC)(GLenum texture);
typedef void (APIENTRY*PFNGLUNIFORM1FPROC)(GLint location, GLfloat v0);
typedef void (APIENTRY*PFNGLUNIFORM2FPROC)(GLint location, GLfloat v0, GLfloat v1);
typedef void (APIENTRY*PFNGLUNIFORM3FPROC)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
typedef void (APIENTRY*PFNGLUNIFORM4FPROC)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
typedef void (APIENTRY*PFNGLUNIFORM1IPROC)(GLint location, GLint v0);
typedef void (APIENTRY*PFNGLUNIFORM2IPROC)(GLint location, GLint v0, GLint v1);
typedef void (APIENTRY*PFNGLUNIFORM3IPROC)(GLint location, GLint v0, GLint v1, GLint v2);
typedef void (APIENTRY*PFNGLUNIFORM4IPROC)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
typedef void (APIENTRY*PFNGLUNIFORM1FVPROC)(GLint location, GLsizei count, const GLfloat *value);
typedef void (APIENTRY*PFNGLUNIFORM2FVPROC)(GLint location, GLsizei count, const GLfloat *value);
typedef void (APIENTRY*PFNGLUNIFORM3FVPROC)(GLint location, GLsizei count, const GLfloat *value);
typedef void (APIENTRY*PFNGLUNIFORM4FVPROC)(GLint location, GLsizei count, const GLfloat *value);
typedef void (APIENTRY*PFNGLUNIFORM1IVPROC)(GLint location, GLsizei count, const GLint *value);
typedef void (APIENTRY*PFNGLUNIFORM2IVPROC)(GLint location, GLsizei count, const GLint *value);
typedef void (APIENTRY*PFNGLUNIFORM3IVPROC)(GLint location, GLsizei count, const GLint *value);
typedef void (APIENTRY*PFNGLUNIFORM4IVPROC)(GLint location, GLsizei count, const GLint *value);
typedef void (APIENTRY*PFNGLUNIFORMMATRIX2FVPROC)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
typedef void (APIENTRY*PFNGLUNIFORMMATRIX3FVPROC)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
typedef void (APIENTRY*PFNGLUNIFORMMATRIX4FVPROC)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
typedef void (APIENTRY*PFNGLVALIDATEPROGRAMPROC)(GLuint program);
typedef GLint (APIENTRY*PFNGLGETUNIFORMLOCATIONPROC)(GLuint program, const GLchar *name);
typedef void (APIENTRY*PFNGLGENFRAMEBUFFERSPROC)(GLsizei n, GLuint *framebuffers);
typedef void (APIENTRY*PFNGLBINDFRAMEBUFFERPROC)(GLenum target, GLuint framebuffer);
typedef void (APIENTRY*PFNGLDELETEFRAMEBUFFERSPROC)(GLsizei n, const GLuint *framebuffers);
typedef void (APIENTRY*PFNGLCLEARBUFFERIVPROC)(GLenum buffer, GLint drawbuffer, const GLint *value);
typedef void (APIENTRY*PFNGLDRAWARRAYSINSTANCEDPROC)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
typedef void (APIENTRY*PFNGLFRAMEBUFFERTEXTUREPROC)(GLenum target, GLenum attachment, GLuint texture, GLint level);
typedef void (APIENTRY*PFNGLFRAMEBUFFERTEXTURE2DPROC)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
typedef void (APIENTRY*PFNGLBINDIMAGETEXTUREPROC)(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
typedef void (APIENTRY*PFNGLBINDBUFFERBASEPROC)(GLenum target, GLuint index, GLuint buffer);
typedef unsigned int (APIENTRY*PFNGLFENCESYNCPROC)(GLenum condition, GLbitfield flags);
typedef void (APIENTRY*PFNGLGETSYNCIVPROC)(GLuint sync, GLenum pname, GLsizei count, GLsizei *length, GLint *values);
typedef void* (APIENTRY*PFNGLMAPBUFFERPROC)(GLenum target, GLenum access);
typedef GLuint (APIENTRY*PFNGLGETPROGRAMRESOURCEINDEXPROC) (GLuint program, GLenum programInterface, const GLchar *name);
typedef void (APIENTRY*PFNGLSHADERSTORAGEBLOCKBINDINGPROC) (GLuint program, GLuint storageBlockIndex, GLuint storageBlockBinding);
typedef void (APIENTRY*PFNGLBINDBUFFERRANGEPROC)(GLenum target, GLuint index, GLuint buffer, GLint offset, GLsizeiptr size);
typedef void (APIENTRY*PFNGLGETBUFFERSUBDATAPROC)(GLenum target, GLint offset, GLsizei size, void *data);
typedef void (APIENTRY*PFNGLCLAMPCOLORPROC)(GLenum target, GLenum clamp);
typedef void (APIENTRY*PFNGLTEXIMAGE3DPROC)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
typedef void (APIENTRY*PFNGLTEXSUBIMAGE3DPROC)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
typedef void (APIENTRY*PFNGLTEXSTORAGE3DPROC)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
typedef void (APIENTRY*PFNGLDRAWBUFFERSPROC)(GLsizei n, const GLenum *bufs);
typedef void (APIENTRY*PFNGLGENRENDERBUFFERSPROC)(GLsizei n, GLuint *renderbuffers);
typedef void (APIENTRY*PFNGLBINDRENDERBUFFERPROC)(GLenum target, GLuint renderbuffer);
typedef void (APIENTRY*PFNGLRENDERBUFFERSTORAGEPROC)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
typedef void (APIENTRY*PFNGLFRAMEBUFFERRENDERBUFFERPROC)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
typedef void (APIENTRY*PFNGLGENERATEMIPMAPPROC)(GLenum target);
typedef void (APIENTRY*PFNGLGETTEXTUREIMAGEPROC) (GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
typedef void (APIENTRY*PFNGLGETTEXTURESUBIMAGEPROC) (GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
typedef void (APIENTRY*PFNGLDISABLEVERTEXATTRIBARRAYPROC) (GLuint index);
typedef void (APIENTRY*PFNGLBUFFERSUBDATAPROC) (GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
typedef void (APIENTRY*PFNGLBLENDFUNCIPROC) (GLuint buf, GLenum src, GLenum dst);
typedef void (APIENTRY*PFNGLFRAMEBUFFERTEXTURELAYERPROC)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
typedef void (APIENTRY*PFNGLGETSHADERIVPROC) (GLuint shader, GLenum pname, GLint *params);
typedef void (APIENTRY*PFNGLGETPROGRAMIVPROC) (GLuint program, GLenum pname, GLint *params);
typedef GLuint (APIENTRY*PFNGLGETUNIFORMBLOCKINDEXPROC) (GLuint program, const GLchar *uniformBlockName);
typedef void (APIENTRY*PFNGLUNIFORMBLOCKBINDINGPROC) (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);

PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
PFNGLBUFFERSUBDATAPROC glBufferSubData;

PFNGLCREATESHADERPROC glCreateShader;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLATTACHSHADERPROC glAttachShader;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLDETACHSHADERPROC glDetachShader;
PFNGLDELETEPROGRAMPROC glDeleteProgram;
PFNGLDELETESHADERPROC glDeleteShader;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLGETPROGRAMIVPROC glGetProgramiv;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLACTIVETEXTUREPROC glActiveTexture;
PFNGLTEXIMAGE3DPROC glTexImage3D;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
PFNGLUNIFORM1FPROC glUniform1f;
PFNGLUNIFORM2FPROC glUniform2f;
PFNGLUNIFORM3FPROC glUniform3f;
PFNGLUNIFORM4FPROC glUniform4f;
PFNGLUNIFORM1IPROC glUniform1i;
PFNGLUNIFORM2IPROC glUniform2i;
PFNGLUNIFORM3IPROC glUniform3i;
PFNGLUNIFORM4IPROC glUniform4i;
PFNGLUNIFORM1FVPROC glUniform1fv;
PFNGLUNIFORM2FVPROC glUniform2fv;
PFNGLUNIFORM3FVPROC glUniform3fv;
PFNGLUNIFORM4FVPROC glUniform4fv;
PFNGLUNIFORM1IVPROC glUniform1iv;
PFNGLUNIFORM2IVPROC glUniform2iv;
PFNGLUNIFORM3IVPROC glUniform3iv;
PFNGLUNIFORM4IVPROC glUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
PFNGLVALIDATEPROGRAMPROC glValidateProgram;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;

PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
PFNGLCLEARBUFFERIVPROC glClearBufferiv;
PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
PFNGLBINDIMAGETEXTUREPROC glBindImageTexture;
PFNGLBINDBUFFERBASEPROC glBindBufferBase;
PFNGLDRAWBUFFERSPROC glDrawBuffers;
PFNGLFENCESYNCPROC glFenceSync;
PFNGLGETSYNCIVPROC glGetSynciv;
PFNGLMAPBUFFERPROC glMapBuffer;
PFNGLGETPROGRAMRESOURCEINDEXPROC glGetProgramResourceIndex;
PFNGLSHADERSTORAGEBLOCKBINDINGPROC glShaderStorageBlockBinding;
PFNGLBINDBUFFERRANGEPROC glBindBufferRange;
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
PFNGLCLAMPCOLORPROC glClampColor;
PFNGLTEXSTORAGE3DPROC glTexStorage3D;
PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
PFNGLGETTEXTUREIMAGEPROC glGetTextureImage;
PFNGLGETTEXTURESUBIMAGEPROC glGetTextureSubImage;
PFNGLBLENDFUNCIPROC glBlendFunci;
PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex;
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding;

void glan_load(){
glCreateShader=(PFNGLCREATESHADERPROC)wglGetProcAddress("glCreateShader");
glShaderSource=(PFNGLSHADERSOURCEPROC)wglGetProcAddress("glShaderSource");
glCompileShader=(PFNGLCOMPILESHADERPROC)wglGetProcAddress("glCompileShader");
glCreateProgram=(PFNGLCREATEPROGRAMPROC)wglGetProcAddress("glCreateProgram");
glAttachShader=(PFNGLATTACHSHADERPROC)wglGetProcAddress("glAttachShader");
glLinkProgram=(PFNGLLINKPROGRAMPROC)wglGetProcAddress("glLinkProgram");
glUseProgram=(PFNGLUSEPROGRAMPROC)wglGetProcAddress("glUseProgram");
glDetachShader=(PFNGLDETACHSHADERPROC)wglGetProcAddress("glDetachShader");
glDeleteProgram=(PFNGLDELETEPROGRAMPROC)wglGetProcAddress("glDeleteProgram");
glDeleteShader=(PFNGLDELETESHADERPROC)wglGetProcAddress("glDeleteShader");
glGetShaderiv=(PFNGLGETSHADERIVPROC)wglGetProcAddress("glGetShaderiv");
glGetProgramiv=(PFNGLGETPROGRAMIVPROC)wglGetProcAddress("glGetProgramiv");
glVertexAttribPointer=(PFNGLVERTEXATTRIBPOINTERPROC)wglGetProcAddress("glVertexAttribPointer");
glEnableVertexAttribArray=(PFNGLENABLEVERTEXATTRIBARRAYPROC)wglGetProcAddress("glEnableVertexAttribArray");
glGenVertexArrays=(PFNGLGENVERTEXARRAYSPROC)wglGetProcAddress("glGenVertexArrays");
glBindVertexArray=(PFNGLBINDVERTEXARRAYPROC)wglGetProcAddress("glBindVertexArray");
glBindBuffer=(PFNGLBINDBUFFERPROC)wglGetProcAddress("glBindBuffer");
glBufferData=(PFNGLBUFFERDATAPROC)wglGetProcAddress("glBufferData");
glGenBuffers=(PFNGLGENBUFFERSPROC)wglGetProcAddress("glGenBuffers");
glActiveTexture=(PFNGLACTIVETEXTUREPROC)wglGetProcAddress("glActiveTexture");
glUniform1f=(PFNGLUNIFORM1FPROC)wglGetProcAddress("glUniform1f");
glUniform2f=(PFNGLUNIFORM2FPROC)wglGetProcAddress("glUniform2f");
glUniform3f=(PFNGLUNIFORM3FPROC)wglGetProcAddress("glUniform3f");
glUniform4f=(PFNGLUNIFORM4FPROC)wglGetProcAddress("glUniform4f");
glUniform1i=(PFNGLUNIFORM1IPROC)wglGetProcAddress("glUniform1i");
glUniform2i=(PFNGLUNIFORM2IPROC)wglGetProcAddress("glUniform2i");
glUniform3i=(PFNGLUNIFORM3IPROC)wglGetProcAddress("glUniform3i");
PFNGLUNIFORM4IPROC glUniform4i=(PFNGLUNIFORM4IPROC)wglGetProcAddress("glUniform4i");
glUniform1fv=(PFNGLUNIFORM1FVPROC)wglGetProcAddress("glUniform1fv");
glUniform2fv=(PFNGLUNIFORM2FVPROC)wglGetProcAddress("glUniform2fv");
glUniform3fv=(PFNGLUNIFORM3FVPROC)wglGetProcAddress("glUniform3fv");
glUniform4fv=(PFNGLUNIFORM4FVPROC)wglGetProcAddress("glUniform4fv");
glUniform1iv=(PFNGLUNIFORM1IVPROC)wglGetProcAddress("glUniform1iv");
glUniform2iv=(PFNGLUNIFORM2IVPROC)wglGetProcAddress("glUniform2iv");
glUniform3iv=(PFNGLUNIFORM3IVPROC)wglGetProcAddress("glUniform3iv");
glUniform4iv=(PFNGLUNIFORM4IVPROC)wglGetProcAddress("glUniform4iv");
glUniformMatrix2fv=(PFNGLUNIFORMMATRIX2FVPROC)wglGetProcAddress("glUniformMatrix2fv");
glUniformMatrix3fv=(PFNGLUNIFORMMATRIX3FVPROC)wglGetProcAddress("glUniformMatrix3fv");
glUniformMatrix4fv=(PFNGLUNIFORMMATRIX4FVPROC)wglGetProcAddress("glUniformMatrix4fv");
glValidateProgram=(PFNGLVALIDATEPROGRAMPROC)wglGetProcAddress("glValidateProgram");
glGetUniformLocation=(PFNGLGETUNIFORMLOCATIONPROC)wglGetProcAddress("glGetUniformLocation");
glTexImage3D=(PFNGLTEXIMAGE3DPROC)wglGetProcAddress("glTexImage3D");
glTexSubImage3D=(PFNGLTEXSUBIMAGE3DPROC)wglGetProcAddress("glTexSubImage3D");

glDrawArraysInstanced=(PFNGLDRAWARRAYSINSTANCEDPROC)wglGetProcAddress("glDrawArraysInstanced");
glDeleteFramebuffers=(PFNGLDELETEFRAMEBUFFERSPROC)wglGetProcAddress("glDeleteFramebuffers");
glBindFramebuffer=(PFNGLBINDFRAMEBUFFERPROC)wglGetProcAddress("glBindFramebuffer");
glGenFramebuffers=(PFNGLGENFRAMEBUFFERSPROC)wglGetProcAddress("glGenFramebuffers");
glDrawBuffers=(PFNGLDRAWBUFFERSPROC)wglGetProcAddress("glDrawBuffers");
glClearBufferiv=(PFNGLCLEARBUFFERIVPROC)wglGetProcAddress("glClearBufferiv");
glFramebufferTexture=(PFNGLFRAMEBUFFERTEXTUREPROC)wglGetProcAddress("glFramebufferTexture");
glFramebufferTexture2D=(PFNGLFRAMEBUFFERTEXTURE2DPROC)wglGetProcAddress("glFramebufferTexture2D");
glBindImageTexture=(PFNGLBINDIMAGETEXTUREPROC)wglGetProcAddress("glBindImageTexture");
glBindBufferBase=(PFNGLBINDBUFFERBASEPROC)wglGetProcAddress("glBindBufferBase");
glFenceSync=(PFNGLFENCESYNCPROC)wglGetProcAddress("glFenceSync");
glGetSynciv=(PFNGLGETSYNCIVPROC)wglGetProcAddress("glGetSynciv");
glMapBuffer=(PFNGLMAPBUFFERPROC)wglGetProcAddress("glMapBuffer");
glGetProgramResourceIndex=(PFNGLGETPROGRAMRESOURCEINDEXPROC)wglGetProcAddress("glGetProgramResourceIndex");
glShaderStorageBlockBinding=(PFNGLSHADERSTORAGEBLOCKBINDINGPROC)wglGetProcAddress("glShaderStorageBlockBinding");
glBindBufferRange=(PFNGLBINDBUFFERRANGEPROC)wglGetProcAddress("glBindBufferRange");
glGetBufferSubData=(PFNGLGETBUFFERSUBDATAPROC)wglGetProcAddress("glGetBufferSubData");
glClampColor=(PFNGLCLAMPCOLORPROC)wglGetProcAddress("glClampColor");
glFramebufferRenderbuffer=(PFNGLFRAMEBUFFERRENDERBUFFERPROC)wglGetProcAddress("glFramebufferRenderbuffer");
glRenderbufferStorage=(PFNGLRENDERBUFFERSTORAGEPROC)wglGetProcAddress("glRenderbufferStorage");
glBindRenderbuffer=(PFNGLBINDRENDERBUFFERPROC)wglGetProcAddress("glBindRenderbuffer");
glGenRenderbuffers=(PFNGLGENRENDERBUFFERSPROC)wglGetProcAddress("glGenRenderbuffers");
glGenerateMipmap=(PFNGLGENERATEMIPMAPPROC)wglGetProcAddress("glGenerateMipmap");
glGetTextureImage=(PFNGLGETTEXTUREIMAGEPROC)wglGetProcAddress("glGetTextureImage");
glGetTextureSubImage=(PFNGLGETTEXTURESUBIMAGEPROC)wglGetProcAddress("glGetTextureSubImage");
glDisableVertexAttribArray=(PFNGLDISABLEVERTEXATTRIBARRAYPROC)wglGetProcAddress("glDisableVertexAttribArray");
glBufferSubData=(PFNGLBUFFERSUBDATAPROC)wglGetProcAddress("glBufferSubData");
glBlendFunci=(PFNGLBLENDFUNCIPROC)wglGetProcAddress("glBlendFunci");
glFramebufferTextureLayer=(PFNGLFRAMEBUFFERTEXTURELAYERPROC)wglGetProcAddress("glFramebufferTextureLayer");
glGetUniformBlockIndex=(PFNGLGETUNIFORMBLOCKINDEXPROC)wglGetProcAddress("glGetUniformBlockIndex");
glUniformBlockBinding=(PFNGLUNIFORMBLOCKBINDINGPROC)wglGetProcAddress("glUniformBlockBinding");
}
